(define (problem pacmanP)
    (:domain pacmanD)

    (:objects 
             pac1 -pacman
             pac2 -pacman
             dot1 dot2 dot3 dot4 dot5 dot6 dot7 dot8 dot9 dot10 dot11 dot12 dot13 -dot
             loc_x1y1 loc_x1y2 loc_x1y3 loc_x1y4 loc_x2y1 loc_x2y2 loc_x2y3 loc_x2y4 loc_x3y1 loc_x3y2 loc_x3y3 loc_x3y4 loc_x4y1 loc_x4y2 loc_x4y3 loc_x4y4 -loc
    )

    (:init (pacman-at pac1 loc_x4y4)
            (pacman-at pac1 loc_x1y1)

            (south loc_x2y1 loc_x1y1) (east loc_x1y2 loc_x1y1) 
            (south loc_x2y2 loc_x1y2) (west loc_x1y1 loc_x1y2) (east loc_x1y3 loc_x1y2) 
            (south loc_x2y3 loc_x1y3) (west loc_x1y2 loc_x1y3) (east loc_x1y4 loc_x1y3) 
            (south loc_x2y4 loc_x1y4) (west loc_x1y3 loc_x1y4)

            (east loc_x2y2 loc_x2y1) (north loc_x1y1 loc_x2y1) 
            (west loc_x2y1 loc_x2y2) (east loc_x2y3 loc_x2y2) (south loc_x3y2 loc_x2y2) (north loc_x1y2 loc_x2y2) 
            (east loc_x2y4 loc_x2y3) (south loc_x3y3 loc_x2y3) (west loc_x2y2 loc_x2y3) (north loc_x1y3 loc_x2y3) 
            (south loc_x3y4 loc_x2y4) (west loc_x2y3 loc_x2y4) (north loc_x1y4 loc_x2y4)
            
            (east loc_x3y3 loc_x3y2) (south loc_x4y2 loc_x3y2) (north loc_x2y2 loc_x3y2) 
            (east loc_x3y4 loc_x3y3) (south loc_x4y3 loc_x3y3) (west loc_x3y2 loc_x3y3) (north loc_x2y3 loc_x3y3) 
            (south loc_x4y4 loc_x3y4) (west loc_x3y3 loc_x3y4) (north loc_x2y4 loc_x3y4)

            (east loc_x4y2 loc_x4y1) 
            (west loc_x4y1 loc_x4y2) (east loc_x4y3 loc_x4y2) (north loc_x3y2 loc_x4y2) 
            (north loc_x3y3 loc_x4y3) (east loc_x4y4 loc_x4y3) (west loc_x4y2 loc_x4y3) 
            (north loc_x3y4 loc_x4y4) (west loc_x4y3 loc_x4y4)

            (DotAt dot1 loc_x1y2)
            (DotAt dot2 loc_x1y3)
            (DotAt dot3 loc_x1y4)
            (DotAt dot4 loc_x2y1)
            (DotAt dot5 loc_x2y2)
            (DotAt dot6 loc_x2y3)
            (DotAt dot7 loc_x2y4)
            (DotAt dot8 loc_x3y2)
            (DotAt dot9 loc_x3y3)
            (DotAt dot10 loc_x3y4)
            (DotAt dot11 loc_x4y1)
            (DotAt dot12 loc_x4y2)
            (DotAt dot13 loc_x4y3)

            (NotEaten dot1)
            (NotEaten dot2)
            (NotEaten dot3)
            (NotEaten dot4)
            (NotEaten dot5)
            (NotEaten dot6)
            (NotEaten dot7)
            (NotEaten dot8)
            (NotEaten dot9)
            (NotEaten dot10)
            (NotEaten dot11)
            (NotEaten dot12)
            (NotEaten dot13)
    )

    (:goal (and (not (NotEaten dot1))
                (not (NotEaten dot2))
                (not (NotEaten dot3))
                (not (NotEaten dot4))
                (not (NotEaten dot5))
                (not (NotEaten dot6))
                (not (NotEaten dot7))
                (not (NotEaten dot8))
                (not (NotEaten dot9))
                (not (NotEaten dot10))
                (not (NotEaten dot11))
                (not (NotEaten dot12))
                (not (NotEaten dot13))
            )
    )
)
